name: GitHub CI

on: [push]

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jvm: [hotspot, openj9]
        jvmType: [jdk, jre]
        version: [8, 11, 16]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        env:
          jvm: ${{ matrix.jvm }}
          jvmType: ${{ matrix.jvmType }}
          version: ${{ matrix.version }}
        run: |
          cd "${jvm}/${jvmType}${version}"
          docker pull "adoptopenjdk:${version}-${jvmType}-${jvm}"
          docker build --tag "gradle:${jvmType}${version}-${jvm}" .
      - name: test
        env:
          jvm: ${{ matrix.jvm }}
          jvmType: ${{ matrix.jvmType }}
          version: ${{ matrix.version }}
          expectedGradleVersion: 6.8.3
        run: |
          cd test
          ./run.sh "gradle:${jvmType}${version}-${jvm}" "${expectedGradleVersion}"
