name: GitHub CI

on: [push]

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jvm: [hotspot, openj9]
        jvmType: [jdk, jre]
        version: [8, 11, 16]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        env:
          jvm: ${{ matrix.jvm }}
          jvmType: ${{ matrix.jvmType }}
          version: ${{ matrix.version }}
        run: |
          cd "${jvm}/${jvmType}${version}"
          docker pull "adoptopenjdk:${version}-${jvmType}-${jvm}"
          docker build --push --tag "ghcr.io/${{ github.repository_owner }}/gradle:${jvmType}${version}-${jvm}" .
      - name: test
        env:
          jvm: ${{ matrix.jvm }}
          jvmType: ${{ matrix.jvmType }}
          version: ${{ matrix.version }}
          expectedGradleVersion: 7.0-rc-2
        run: |
          cd test
          ./run.sh "gradle:${jvmType}${version}-${jvm}" "${expectedGradleVersion}"
